# Build stage
FROM maven:3.9.11-amazoncorretto-25-alpine AS build
WORKDIR /build
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests

# Runtime stage
FROM amazoncorretto:25-alpine3.22
ARG APP_VERSION=1.0.0
WORKDIR /app
COPY --from=build /build/target/blogapp-*.jar /app/

EXPOSE 8080

ENV DB_URL=jdbc:postgresql://blogsphere:5001/blogspheredb 
ENV JAR_VERSION=${APP_VERSION}

CMD java -jar -Dspring.datasource.url=${DB_URL} blogapp-${JAR_VERSION}.jar
